CREATE SEQUENCE produtoid_seq INCREMENT 1  MINVALUE 1  MAXVALUE 9223372036854775807  START 1 CACHE 1;
CREATE TABLE PRODUTO (ID INT, CODIGO INT, DESCRICAO VARCHAR, DATA_CADASTRO DATE);

CREATE SEQUENCE clienteid_seq INCREMENT 1  MINVALUE 1  MAXVALUE 9223372036854775807  START 1 CACHE 1;
CREATE TABLE CLIENTE (ID INT, CODIGO INT, NOME VARCHAR);

CREATE SEQUENCE pedidoid_seq INCREMENT 1  MINVALUE 1  MAXVALUE 9223372036854775807  START 1 CACHE 1;

CREATE TABLE PEDIDO (ID INT, cliente_id INT , DATA_CADASTRO DATE, VALORPEDIDO NUMERIC(19,5), DESPACHADO BOOLEAN, situacao integer, icms numeric(19,5), icmsst numeric(19,5), ipi numeric(19,5), iss numeric(19,5), constraint pedidoid_pkey primary key (id));

CREATE SEQUENCE itempedidoid_seq INCREMENT 1  MINVALUE 1  MAXVALUE 9223372036854775807  START 1 CACHE 1;

CREATE TABLE ITEMPEDIDO (ID INT , PEDIDO_ID INT , PRODUTO_ID INT , PRECO NUMERIC(19,5), DESCONTO NUMERIC(19,5), SITUACAO INT, constraint itempedidoid_pkey primary key (id));
alter table itempedido add CONSTRAINT itempedido_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES pedido (id) on UPDATE RESTRICT ON DELETE RESTRICT;
alter table itempedido add CONSTRAINT itempedido_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES produto (id) ON UPDATE RESTRICT ON DELETE RESTRICT;